### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by jakubzehner** [Filipstrozik/AdventOfCode2022#1]
### You should add .gitignore to avoid adding compiled code to github, which is located in /out xD

1. create gitignore like this one - https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
2. Execute these commands:

```sh
git rm -r --cached .  
git add .  
git commit -m "Drop files from .gitignore"
```

**Comment by Filipstrozik** [comment]
Wow, thank You Jakub for your advice! I completely agree I will also add inputs to gitignore, because it's forbidden as far as I know.
